window.PROJETORES_DATA = [
  {
    "marca": "Bettdow",
    "modelo": "AC1041",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 510,
    "audio_w": "5",
    "distancia_100pol": "3m",
    "distancia_100pol_m": 3.0,
    "otica_selada": "Não Selada",
    "input_lag_ms": 48.0,
    "ajuste_brilho": "Não",
    "autofoco": "Não",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 99,
    "conectividade": "2xHDMI/2xUSB/AV/P2/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/oVALw1o_4Yk",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 820,
    "preco_max": 850,
    "ali_url": "",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "",
    "ml_url": "https://meli.la/1vrDgrV",
    "shopee_url": "https://s.shopee.com.br/16yG6yQoM",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Bettdow",
    "modelo": "AC1053",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 60hz/1080p 120hz",
    "brilho_ansi": 710,
    "audio_w": "2x10",
    "distancia_100pol": "3.2m",
    "distancia_100pol_m": 3.2,
    "otica_selada": "Não Selada+",
    "input_lag_ms": 10.0,
    "ajuste_brilho": "Sim",
    "autofoco": "Não",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 171,
    "conectividade": "2xHDMI/2xUSB/AV/P2/RJ45/WiFi/BT",
    "tecnologias": "HDR10",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/y4JEW_ocamU",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "6h",
    "preco_min": 807,
    "preco_max": 850,
    "ali_url": "",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "",
    "ml_url": "",
    "shopee_url": "https://s.shopee.com.br/9Uy60nx2YD",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Bettdow",
    "modelo": "AC1060",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 360,
    "audio_w": "3",
    "distancia_100pol": "3.1m",
    "distancia_100pol_m": 3.1,
    "otica_selada": "Selada-",
    "input_lag_ms": 27.0,
    "ajuste_brilho": "Sim",
    "autofoco": "Sim",
    "sistema_operacional": "WhaleOS",
    "consumo_w": 91,
    "conectividade": "HDMI/USB/P2/WiFi/BT",
    "tecnologias": "HDR",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/tRkWxNCDPKM",
    "suporte_giratorio": true,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 600,
    "preco_max": 700,
    "ali_url": "",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "",
    "ml_url": "",
    "shopee_url": "https://s.shopee.com.br/6AdyVCmNOa",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Bettdow",
    "modelo": "AC1061",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 60hz",
    "brilho_ansi": 630,
    "audio_w": "2x10",
    "distancia_100pol": "2.6m",
    "distancia_100pol_m": 2.6,
    "otica_selada": "Selada",
    "input_lag_ms": 32.0,
    "ajuste_brilho": "Sim",
    "autofoco": "Sim",
    "sistema_operacional": "Google TV",
    "consumo_w": 106,
    "conectividade": "HDMI/USB/P2/WiFi/BT",
    "tecnologias": "HDR",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/WBkyufiPeO4",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "6h",
    "preco_min": 1071,
    "preco_max": 1250,
    "ali_url": "",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "",
    "ml_url": "",
    "shopee_url": "https://s.shopee.com.br/2LUvTkd5v2",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 32,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Bettdow",
    "modelo": "AC1066",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 250,
    "audio_w": "5",
    "distancia_100pol": "1.8m",
    "distancia_100pol_m": 1.8,
    "otica_selada": "Não Selada",
    "input_lag_ms": 30.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "WhaleOS",
    "consumo_w": 53,
    "conectividade": "HDMI/USB/P2/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/pEVdHBf6ZXU",
    "suporte_giratorio": true,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 550,
    "preco_max": 620,
    "ali_url": "",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "",
    "ml_url": "",
    "shopee_url": "https://s.shopee.com.br/5L26YD2oG9",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Bettdow",
    "modelo": "AC1071",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 1010,
    "audio_w": "2x5",
    "distancia_100pol": "2.9m",
    "distancia_100pol_m": 2.9,
    "otica_selada": "Selada-",
    "input_lag_ms": 10.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "WhaleOS",
    "consumo_w": 167,
    "conectividade": "2xHDMI/2xUSB/AV/P2/RJ45/WiFi/BT",
    "tecnologias": "HDR10",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/eGwJmw4gsj8",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "6h",
    "preco_min": 1050,
    "preco_max": 1200,
    "ali_url": "",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "",
    "ml_url": "",
    "shopee_url": "https://s.shopee.com.br/6AhbbF12LJ",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Bettdow",
    "modelo": "AC1073",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 15hz",
    "brilho_ansi": 650,
    "audio_w": "2x8",
    "distancia_100pol": "3.1m",
    "distancia_100pol_m": 3.1,
    "otica_selada": "Selada",
    "input_lag_ms": 35.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": null,
    "conectividade": "HDMI/2xUSB/P2/RJ45/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/CPPjiIUp3dY",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "6h",
    "preco_min": 817,
    "preco_max": 1200,
    "ali_url": "",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "",
    "ml_url": "",
    "shopee_url": "https://s.shopee.com.br/60JUs8TGOi",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 32,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Bettdow",
    "modelo": "AC1079",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 820,
    "audio_w": "8",
    "distancia_100pol": "2.8m",
    "distancia_100pol_m": 2.8,
    "otica_selada": "Não Selada+",
    "input_lag_ms": 50.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 123,
    "conectividade": "HDMI/USB/P2/RJ45/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/uJlFbDdvNJE",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "6h",
    "preco_min": 720,
    "preco_max": 800,
    "ali_url": "",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "",
    "ml_url": "",
    "shopee_url": "https://s.shopee.com.br/2g7jQt8Ynh",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Bettdow",
    "modelo": "AC1080",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 720,
    "audio_w": "5.0",
    "distancia_100pol": "3m",
    "distancia_100pol_m": 3.0,
    "otica_selada": "Não Selada+",
    "input_lag_ms": 90.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Android TV",
    "consumo_w": 103,
    "conectividade": "HDMI/2xUSB/AV/P2/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/lkCjWPlswcA",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 630,
    "preco_max": 800,
    "ali_url": "",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "",
    "ml_url": "",
    "shopee_url": "https://s.shopee.com.br/7AaBElehNc",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Bettdow",
    "modelo": "AC1082",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 590,
    "audio_w": "5",
    "distancia_100pol": "3m",
    "distancia_100pol_m": 3.0,
    "otica_selada": "Não Selada",
    "input_lag_ms": 30.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "WhaleOS",
    "consumo_w": 101,
    "conectividade": "2xHDMI/2xUSB/AV/P2/WiFi/BT",
    "tecnologias": "HDR",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/cZWqDeYtdyg",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 830,
    "preco_max": 900,
    "ali_url": "",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "",
    "ml_url": "",
    "shopee_url": "https://s.shopee.com.br/7AWWX2mxVz",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": "basica"
  },
  {
    "marca": "Byintek",
    "modelo": "Love U4",
    "tecnologia": "DLP LED",
    "resolucao_nativa": "1280x720",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 170,
    "audio_w": "3",
    "distancia_100pol": "2.70m",
    "distancia_100pol_m": 2.7,
    "otica_selada": "Selada",
    "input_lag_ms": 30.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 39,
    "conectividade": "HDMI/USB/P2/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/0MIc4SOshTw",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "6h",
    "preco_min": 450,
    "preco_max": 650,
    "ali_url": "https://s.click.aliexpress.com/e/_c3kxoZG3",
    "ali_cupom_loja": "U4BRDR",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "https://s.shopee.com.br/30kZpksZvV",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Byintek",
    "modelo": "Love U12",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 540,
    "audio_w": "2x5",
    "distancia_100pol": "3.10m",
    "distancia_100pol_m": 3.1,
    "otica_selada": "Selada",
    "input_lag_ms": 50.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 130,
    "conectividade": "2xHDMI/2xUSB/AV/P2/RJ45/5.0/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/jRZUQhpTk2g",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "6h",
    "preco_min": 980,
    "preco_max": 1100,
    "ali_url": "https://s.click.aliexpress.com/e/_Dkejizx",
    "ali_cupom_loja": "U12SC25",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "https://s.shopee.com.br/5L8ViQYTqt",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Byintek",
    "modelo": "Love U14",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 790,
    "audio_w": "2x12",
    "distancia_100pol": "2.60m",
    "distancia_100pol_m": 2.6,
    "otica_selada": "Selada",
    "input_lag_ms": 140.0,
    "ajuste_brilho": "Sim",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 183,
    "conectividade": "2xHDMI/USB/P2/SPDIF/RJ45/5.0/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/yBm4zoivDVc",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "6h",
    "preco_min": 1000,
    "preco_max": 1300,
    "ali_url": "https://s.click.aliexpress.com/e/_c3M7l88P",
    "ali_cupom_loja": "U14BRDR",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "https://s.shopee.com.br/50VfJsUyJi",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Byintek",
    "modelo": "Plato T5 MAX",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 610,
    "audio_w": "10",
    "distancia_100pol": "2.60m",
    "distancia_100pol_m": 2.6,
    "otica_selada": "Selada",
    "input_lag_ms": 35.0,
    "ajuste_brilho": "Sim",
    "autofoco": "Sim",
    "sistema_operacional": "Google TV",
    "consumo_w": 116,
    "conectividade": "HDMI/USB/P2/5.0/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/OIOu6h1v8R0",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "6h",
    "preco_min": 1100,
    "preco_max": 1300,
    "ali_url": "https://s.click.aliexpress.com/e/_c3eH7fd5",
    "ali_cupom_loja": "T5MAXM",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "https://s.shopee.com.br/2BBVHmefEU",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Byintek",
    "modelo": "U80 MAX",
    "tecnologia": "DLP LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 60hz",
    "brilho_ansi": 320,
    "audio_w": "2x5",
    "distancia_100pol": "2.75m",
    "distancia_100pol_m": 2.75,
    "otica_selada": "Selada++",
    "input_lag_ms": 35.0,
    "ajuste_brilho": "Sim",
    "autofoco": "Sim",
    "sistema_operacional": "Google TV",
    "consumo_w": 35,
    "conectividade": "HDMI/USB/P2/WiFi/BT",
    "tecnologias": "3D",
    "bateria": true,
    "cap_bateria": "15000mAh",
    "video_url": "https://youtu.be/FsHSDTwIg3g",
    "suporte_giratorio": true,
    "audio_qualidade": "",
    "uso_continuo": "12h",
    "preco_min": 1500,
    "preco_max": 2500,
    "ali_url": "https://s.click.aliexpress.com/e/_c3S6SLE7",
    "ali_cupom_loja": "U80MAXDR",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "https://s.shopee.com.br/AADlTRa13k",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 32,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Byintek",
    "modelo": "U90 MAX",
    "tecnologia": "DLP LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 60hz",
    "brilho_ansi": 440,
    "audio_w": "2x10",
    "distancia_100pol": "2.75m",
    "distancia_100pol_m": 2.75,
    "otica_selada": "Selada++",
    "input_lag_ms": 25.0,
    "ajuste_brilho": "Sim",
    "autofoco": "Sim",
    "sistema_operacional": "Google TV",
    "consumo_w": 57,
    "conectividade": "HDMI/2xUSB/P2/USB-C/WiFi/BT",
    "tecnologias": "HDR10, MEMC",
    "bateria": true,
    "cap_bateria": "20000mAh",
    "video_url": "https://youtu.be/5-tIyyzXllk",
    "suporte_giratorio": true,
    "audio_qualidade": "",
    "uso_continuo": "12h",
    "preco_min": 1800,
    "preco_max": 2700,
    "ali_url": "https://s.click.aliexpress.com/e/_c3ZZIwIb",
    "ali_cupom_loja": "U90MAXDR",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "https://s.shopee.com.br/5L8ViQYTqt",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 32,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Byintek",
    "modelo": "X30",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 30hz",
    "brilho_ansi": 450,
    "audio_w": "10",
    "distancia_100pol": "3.10m",
    "distancia_100pol_m": 3.1,
    "otica_selada": "Não Selada+",
    "input_lag_ms": 37.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Linux",
    "consumo_w": 140,
    "conectividade": "HDMI/2xUSB/P2/5.0/WiFi/BT",
    "tecnologias": "HDR10, Dolby Audio, MEMC",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/Qf1fj50wzis",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "6h",
    "preco_min": 1000,
    "preco_max": 1200,
    "ali_url": "https://s.click.aliexpress.com/e/_onpRnZ2",
    "ali_cupom_loja": "X30SC20",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Caiwei",
    "modelo": "A8+",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 60hz",
    "brilho_ansi": 560,
    "audio_w": "2x10",
    "distancia_100pol": "3.10m",
    "distancia_100pol_m": 3.1,
    "otica_selada": "Selada-",
    "input_lag_ms": 35.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Android TV",
    "consumo_w": 140,
    "conectividade": "HDMI/USB/AV/VGA/P2/5.0/WiFi/BT/NFC",
    "tecnologias": "HDR, Dolby Audio",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/2QE6-oOmsTc",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 1650,
    "preco_max": 1800,
    "ali_url": "https://s.click.aliexpress.com/e/_c2RFkiHH",
    "ali_cupom_loja": "SDB47L51GUSP",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 16,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Dangbei",
    "modelo": "Mars Pro 2",
    "tecnologia": "DLP Laser",
    "resolucao_nativa": "3840x2160",
    "resolucao_max": "4k 60hz/1080p 240hz",
    "brilho_ansi": 2600,
    "audio_w": "2x12",
    "distancia_100pol": "2.70m",
    "distancia_100pol_m": 2.7,
    "otica_selada": "Selada++",
    "input_lag_ms": 16.0,
    "ajuste_brilho": "Sim",
    "autofoco": "Sim",
    "sistema_operacional": "Google TV",
    "consumo_w": 154,
    "conectividade": "2xHDMI/2xUSB/P2/Óptica/RJ45/WiFi/BT",
    "tecnologias": "HDR, MEMC, Dolby Audio, DTS, 3D",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/XrWcccgRpGY",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "12h",
    "preco_min": 7400,
    "preco_max": 8500,
    "ali_url": "https://s.click.aliexpress.com/e/_c4ttoUvH",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 32,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Everycom",
    "modelo": "Cubelite E1",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 60hz",
    "brilho_ansi": 1375,
    "audio_w": "3x10",
    "distancia_100pol": "2.8m",
    "distancia_100pol_m": 2.8,
    "otica_selada": "Selada",
    "input_lag_ms": 35.0,
    "ajuste_brilho": "Sim",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 196,
    "conectividade": "HDMI/2xUSB/P2/RJ45/WiFi/BT",
    "tecnologias": "HDR10, HLG",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/1_UL8d8bkZk",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "8h",
    "preco_min": 1900,
    "preco_max": 2000,
    "ali_url": "",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "",
    "ml_url": "https://meli.la/19nFftt",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 3,
    "armazenamento_gb": 64,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Everycom",
    "modelo": "Cubelite MAX",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 60hz",
    "brilho_ansi": 1475,
    "audio_w": "3x10",
    "distancia_100pol": "2.8m",
    "distancia_100pol_m": 2.8,
    "otica_selada": "Selada",
    "input_lag_ms": 35.0,
    "ajuste_brilho": "Sim",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 203,
    "conectividade": "HDMI/2xUSB/P2/RJ45/WiFi/BT",
    "tecnologias": "HDR",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/_ghhW7yBUnU",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "8h",
    "preco_min": 2000,
    "preco_max": 2200,
    "ali_url": "",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "",
    "ml_url": "https://meli.la/1faS5r2",
    "shopee_url": "https://s.shopee.com.br/1Vvn2bmJMK",
    "amazon_url": "",
    "ram_gb": 3,
    "armazenamento_gb": 128,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Everycom",
    "modelo": "R16",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 30hz",
    "brilho_ansi": 360,
    "audio_w": "2x3",
    "distancia_100pol": "2.6m",
    "distancia_100pol_m": 2.6,
    "otica_selada": "Não Selada",
    "input_lag_ms": 55.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 53,
    "conectividade": "HDMI/USB/P2/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/zxj2ZplQalg",
    "suporte_giratorio": true,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 529,
    "preco_max": 700,
    "ali_url": "https://s.click.aliexpress.com/e/_mP2PSiD",
    "ali_cupom_loja": "6G69JELT19NQ",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Everycom",
    "modelo": "YG710W",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 750,
    "audio_w": "20",
    "distancia_100pol": "3.0m",
    "distancia_100pol_m": 3.0,
    "otica_selada": "Selada+",
    "input_lag_ms": 75.0,
    "ajuste_brilho": "Sim",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 96,
    "conectividade": "2xHDMI/USB/AV/P2/RJ45/WiFi/BT",
    "tecnologias": "HDR10",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/YveED_mcchI",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "8h",
    "preco_min": null,
    "preco_max": null,
    "ali_url": "",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 32,
    "status": "importado",
    "link_importado": "https://s.click.aliexpress.com/e/_c4mEkazd",
    "bolsa": ""
  },
  {
    "marca": "FlixTone",
    "modelo": "D9W Mini",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 1150,
    "audio_w": "5",
    "distancia_100pol": "2.75m",
    "distancia_100pol_m": 2.75,
    "otica_selada": "Selada-",
    "input_lag_ms": 40.0,
    "ajuste_brilho": "Sim",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 145,
    "conectividade": "2xHDMI/2xUSB/AV/P2/RJ45/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/gOqMZHhRbY8",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "6h",
    "preco_min": 950,
    "preco_max": 1200,
    "ali_url": "https://s.click.aliexpress.com/e/_mrnkrDP",
    "ali_cupom_loja": "JIY2BPTRQBBA",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 32,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "FlixTone",
    "modelo": "D9W Ultra",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 1600,
    "audio_w": "3x10",
    "distancia_100pol": "2.8m",
    "distancia_100pol_m": 2.8,
    "otica_selada": "Selada",
    "input_lag_ms": 35.0,
    "ajuste_brilho": "Sim",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 200,
    "conectividade": "HDMI/2xUSB/P2/RJ45/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/HMJz5gjEc8w",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "8h",
    "preco_min": 1250,
    "preco_max": 1700,
    "ali_url": "https://s.click.aliexpress.com/e/_oBLMuz0",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 3,
    "armazenamento_gb": 128,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Formovie",
    "modelo": "Cinema Edge",
    "tecnologia": "DLP Laser",
    "resolucao_nativa": "3840x2160",
    "resolucao_max": "4k 60hz/1080p 120hz",
    "brilho_ansi": 2100,
    "audio_w": "2x15",
    "distancia_100pol": "0.2m",
    "distancia_100pol_m": 0.2,
    "otica_selada": "Selada++",
    "input_lag_ms": 30.0,
    "ajuste_brilho": "Sim",
    "autofoco": "Sim",
    "sistema_operacional": "Google TV",
    "consumo_w": 250,
    "conectividade": "3xHDMI/2xUSB/P2/Óptica/RJ45/WiFi/BT",
    "tecnologias": "HDR10, HLG, Dolby Audio, DTS, MEMC",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/6D61XvqHsuE",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "12h",
    "preco_min": 9000,
    "preco_max": 12000,
    "ali_url": "https://s.click.aliexpress.com/e/_c4tUeiIB",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 32,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Formovie",
    "modelo": "Xming Episode One",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 120hz",
    "brilho_ansi": 170,
    "audio_w": "2x3",
    "distancia_100pol": "2.7m",
    "distancia_100pol_m": 2.7,
    "otica_selada": "Selada+",
    "input_lag_ms": 10.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Google TV",
    "consumo_w": 45,
    "conectividade": "HDMI/USB/WiFi/BT",
    "tecnologias": "HDR10, Dolby Audio",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/eUMeawsJ0ek",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "8h",
    "preco_min": 1000,
    "preco_max": 2200,
    "ali_url": "https://s.click.aliexpress.com/e/_c4qrQEtz",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 16,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Formovie",
    "modelo": "Xming Page One",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 120hz",
    "brilho_ansi": 450,
    "audio_w": "2x5",
    "distancia_100pol": "2.8m",
    "distancia_100pol_m": 2.8,
    "otica_selada": "Selada+",
    "input_lag_ms": 10.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Google TV",
    "consumo_w": 100,
    "conectividade": "HDMI/USB/P2/WiFi/BT",
    "tecnologias": "HDR10, Dolby Audio",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/inSqZQPCGsw",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "8h",
    "preco_min": 1500,
    "preco_max": 2200,
    "ali_url": "https://s.click.aliexpress.com/e/_c3K8fckj",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 16,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Horlat",
    "modelo": "T09",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 680,
    "audio_w": "2x5",
    "distancia_100pol": "3.1m",
    "distancia_100pol_m": 3.1,
    "otica_selada": "Não Selada",
    "input_lag_ms": 40.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 100,
    "conectividade": "2xHDMI/USB/AV/P2/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/ExXDTuN4s_k",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": null,
    "preco_max": null,
    "ali_url": "https://s.click.aliexpress.com/e/_mNnYBH5",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 32,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Horlat",
    "modelo": "T9N",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 830,
    "audio_w": "2x5",
    "distancia_100pol": "3.1m",
    "distancia_100pol_m": 3.1,
    "otica_selada": "Não Selada",
    "input_lag_ms": 40.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 110,
    "conectividade": "2xHDMI/USB/AV/P2/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/fOzOQLstyXc",
    "suporte_giratorio": true,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 780,
    "preco_max": 900,
    "ali_url": "https://s.click.aliexpress.com/e/_mNnYBH5",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 64,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Jenovox",
    "modelo": "M5000 Mini",
    "tecnologia": "DLP LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 460,
    "audio_w": "2x3",
    "distancia_100pol": "2.7m",
    "distancia_100pol_m": 2.7,
    "otica_selada": "Selada++",
    "input_lag_ms": 65.0,
    "ajuste_brilho": "Sim",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 58,
    "conectividade": "HDMI/USB/P2/USB-C/WiFi/BT",
    "tecnologias": "",
    "bateria": true,
    "cap_bateria": "9000mAh",
    "video_url": "https://youtu.be/as4btwnIWHw",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "12h",
    "preco_min": 1800,
    "preco_max": 2200,
    "ali_url": "https://pt.aliexpress.com/item/1005004398816132.html",
    "ali_cupom_loja": "0YJD2575PU56",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 32,
    "status": "nacional",
    "link_importado": "",
    "bolsa": "premium"
  },
  {
    "marca": "Magcubic",
    "modelo": "HY300",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1280x720",
    "resolucao_max": "4k 30hz",
    "brilho_ansi": 120,
    "audio_w": "3.0",
    "distancia_100pol": "2.8m",
    "distancia_100pol_m": 2.8,
    "otica_selada": "Não Selada",
    "input_lag_ms": 180.0,
    "ajuste_brilho": "Não",
    "autofoco": "Não",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 50,
    "conectividade": "HDMI/USB/P2/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/QSO1DqjaJvo",
    "suporte_giratorio": true,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 200,
    "preco_max": 250,
    "ali_url": "https://s.click.aliexpress.com/e/_c4CNJtO3",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "https://s.shopee.com.br/8V5WHhBPSl",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Magcubic",
    "modelo": "HY310",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 30hz",
    "brilho_ansi": 220,
    "audio_w": "5.0",
    "distancia_100pol": "1.8m",
    "distancia_100pol_m": 1.8,
    "otica_selada": "Não Selada",
    "input_lag_ms": 110.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 45,
    "conectividade": "HDMI/USB/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/KnigQCaR0R8",
    "suporte_giratorio": true,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 400,
    "preco_max": 500,
    "ali_url": "https://s.click.aliexpress.com/e/_c3XIBknv",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "https://s.shopee.com.br/2LUswBGiBw",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Magcubic",
    "modelo": "HY310X",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 30hz",
    "brilho_ansi": 230,
    "audio_w": "5.0",
    "distancia_100pol": "1.8m",
    "distancia_100pol_m": 1.8,
    "otica_selada": "Não Selada",
    "input_lag_ms": 110.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": null,
    "conectividade": "HDMI/USB/P2/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/CLm_kn8sRmo",
    "suporte_giratorio": true,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 400,
    "preco_max": 500,
    "ali_url": "",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "importado",
    "link_importado": "https://s.click.aliexpress.com/e/_okS8x0W",
    "bolsa": ""
  },
  {
    "marca": "Magcubic",
    "modelo": "HY320",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 30hz",
    "brilho_ansi": 250,
    "audio_w": "3.0",
    "distancia_100pol": "2.7m",
    "distancia_100pol_m": 2.7,
    "otica_selada": "Não Selada",
    "input_lag_ms": 180.0,
    "ajuste_brilho": "Não",
    "autofoco": "Não",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 55,
    "conectividade": "HDMI/USB/P2/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/szW_QNBn7gc",
    "suporte_giratorio": true,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 400,
    "preco_max": 600,
    "ali_url": "https://s.click.aliexpress.com/e/_Dna9H9n",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Magcubic",
    "modelo": "HY320 Mini",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1280x720",
    "resolucao_max": "4k 30hz",
    "brilho_ansi": 170,
    "audio_w": "3.0",
    "distancia_100pol": "2.7m",
    "distancia_100pol_m": 2.7,
    "otica_selada": "Não Selada",
    "input_lag_ms": 110.0,
    "ajuste_brilho": "Não",
    "autofoco": "Não",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 50,
    "conectividade": "HDMI/USB/P2/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/3ZS2c2XEars",
    "suporte_giratorio": true,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 300,
    "preco_max": 350,
    "ali_url": "https://s.click.aliexpress.com/e/_c3UDSVwj",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "https://s.shopee.com.br/901msxANBT",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Magcubic",
    "modelo": "HY320 NTV",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 285,
    "audio_w": "3.0",
    "distancia_100pol": "2.7m",
    "distancia_100pol_m": 2.7,
    "otica_selada": "Não Selada",
    "input_lag_ms": 30.0,
    "ajuste_brilho": "Não",
    "autofoco": "Não",
    "sistema_operacional": "WhaleOS",
    "consumo_w": 60,
    "conectividade": "HDMI/USB/P2/WiFi/BT",
    "tecnologias": "HDR10",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/F7G0jkyQXKQ",
    "suporte_giratorio": true,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 500,
    "preco_max": 700,
    "ali_url": "",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "importado",
    "link_importado": "https://s.click.aliexpress.com/e/_c4DHxhJd",
    "bolsa": ""
  },
  {
    "marca": "Magcubic",
    "modelo": "HY350",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 30hz",
    "brilho_ansi": 340,
    "audio_w": "5.0",
    "distancia_100pol": "2.9m",
    "distancia_100pol_m": 2.9,
    "otica_selada": "Não Selada",
    "input_lag_ms": 180.0,
    "ajuste_brilho": "Não",
    "autofoco": "",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 80,
    "conectividade": "HDMI/USB/P2/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/ZFXHS2uBRWo",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 550,
    "preco_max": 570,
    "ali_url": "https://s.click.aliexpress.com/e/_c3GbbpqT",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "https://s.shopee.com.br/5q4l7TeLMm",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 32,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Magcubic",
    "modelo": "HY350 MAX",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 30hz",
    "brilho_ansi": 610,
    "audio_w": "15.0",
    "distancia_100pol": "2.4m",
    "distancia_100pol_m": 2.4,
    "otica_selada": "Não Selada+",
    "input_lag_ms": 60.0,
    "ajuste_brilho": "Sim",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 100,
    "conectividade": "HDMI/USB/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/4Net__jfo4A",
    "suporte_giratorio": true,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 700,
    "preco_max": 900,
    "ali_url": "",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 16,
    "status": "importado",
    "link_importado": "https://s.click.aliexpress.com/e/_c4slluCx",
    "bolsa": ""
  },
  {
    "marca": "Magcubic",
    "modelo": "HY450",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 30hz",
    "brilho_ansi": 620,
    "audio_w": "2x10",
    "distancia_100pol": "1.3m",
    "distancia_100pol_m": 1.3,
    "otica_selada": "Não Selada",
    "input_lag_ms": 70.0,
    "ajuste_brilho": "Sim",
    "autofoco": "Não",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 116,
    "conectividade": "HDMI/USB/P2/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/gMy4NQWwFMI",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 730,
    "preco_max": 900,
    "ali_url": "https://s.click.aliexpress.com/e/_msjwueh",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "https://s.shopee.com.br/3VgqM6cqng",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 32,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Magcubic",
    "modelo": "HY450C",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 30hz",
    "brilho_ansi": 720,
    "audio_w": "2x10",
    "distancia_100pol": "1.3m",
    "distancia_100pol_m": 1.3,
    "otica_selada": "Não Selada",
    "input_lag_ms": 70.0,
    "ajuste_brilho": "Sim",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": null,
    "conectividade": "HDMI/USB/P2/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/fep7bqCyzns",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 950,
    "preco_max": 1000,
    "ali_url": "https://s.click.aliexpress.com/e/_c4pYzVDZ",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "https://s.shopee.com.br/7fWPJrfwbw",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 32,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Magcubic",
    "modelo": "HY450 MAX",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 30hz",
    "brilho_ansi": 900,
    "audio_w": "12.0",
    "distancia_100pol": "2.4m",
    "distancia_100pol_m": 2.4,
    "otica_selada": "Não Selada+",
    "input_lag_ms": 75.0,
    "ajuste_brilho": "Sim",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": null,
    "conectividade": "HDMI/USB/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/hPllH1sVr1A",
    "suporte_giratorio": true,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 1300,
    "preco_max": 1700,
    "ali_url": "",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 16,
    "status": "importado",
    "link_importado": "https://s.click.aliexpress.com/e/_c3qFOuAf",
    "bolsa": ""
  },
  {
    "marca": "Magcubic",
    "modelo": "L018",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 30hz",
    "brilho_ansi": 400,
    "audio_w": "5.0",
    "distancia_100pol": "2.5m",
    "distancia_100pol_m": 2.5,
    "otica_selada": "Não Selada",
    "input_lag_ms": 160.0,
    "ajuste_brilho": "Sim",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": null,
    "conectividade": "HDMI/USB/P2/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/HZMeDSX3ao4",
    "suporte_giratorio": true,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 500,
    "preco_max": 650,
    "ali_url": "https://s.click.aliexpress.com/e/_okGv4NN",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Progaga",
    "modelo": "PG310",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1280x720",
    "resolucao_max": "4k 30hz",
    "brilho_ansi": 185,
    "audio_w": "3",
    "distancia_100pol": "2m",
    "distancia_100pol_m": 2.0,
    "otica_selada": "Não Selada",
    "input_lag_ms": 160.0,
    "ajuste_brilho": "Não",
    "autofoco": "Não",
    "sistema_operacional": "Android não homologado",
    "consumo_w": null,
    "conectividade": "HDMI/USB/P2/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/jmgwg0bU8A4",
    "suporte_giratorio": true,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 280,
    "preco_max": 330,
    "ali_url": "https://s.click.aliexpress.com/e/_c3Kl66kT",
    "ali_cupom_loja": "SCHARD31F",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "https://s.shopee.com.br/20oLbub3fc",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Progaga",
    "modelo": "PG370",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 30hz",
    "brilho_ansi": 240,
    "audio_w": "5",
    "distancia_100pol": "1.8m",
    "distancia_100pol_m": 1.8,
    "otica_selada": "Não Selada",
    "input_lag_ms": 150.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 53,
    "conectividade": "HDMI/USB/P2/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/FRiY0ahQ7Ws",
    "suporte_giratorio": true,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 400,
    "preco_max": 450,
    "ali_url": "https://s.click.aliexpress.com/e/_c3xNjJoP",
    "ali_cupom_loja": "SCHARD37F",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "https://s.shopee.com.br/6Kw1feI48u",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Progaga",
    "modelo": "PG610W",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 830,
    "audio_w": "10",
    "distancia_100pol": "2.8m",
    "distancia_100pol_m": 2.8,
    "otica_selada": "Selada-",
    "input_lag_ms": 50.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 120,
    "conectividade": "HDMI/USB/P2/RJ45/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/L_errvHyeyI",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "6h",
    "preco_min": 1050,
    "preco_max": 1200,
    "ali_url": "https://s.click.aliexpress.com/e/_c3towXAT",
    "ali_cupom_loja": "SCHARD61F",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 32,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Thundeal",
    "modelo": "TD80PRO",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 30hz",
    "brilho_ansi": 260,
    "audio_w": "8",
    "distancia_100pol": "2.9m",
    "distancia_100pol_m": 2.9,
    "otica_selada": "Não Selada",
    "input_lag_ms": 110.0,
    "ajuste_brilho": "Não",
    "autofoco": "Não",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 60,
    "conectividade": "HDMI/USB/P2/RJ45/WiFi/BT",
    "tecnologias": "HDR",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/ytkdvF1rmQw",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 450,
    "preco_max": 600,
    "ali_url": "https://s.click.aliexpress.com/e/_c3k5Ektd",
    "ali_cupom_loja": "SCHARD80PF",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Thundeal",
    "modelo": "TD80W",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 30hz",
    "brilho_ansi": 180,
    "audio_w": "3",
    "distancia_100pol": "2.9m",
    "distancia_100pol_m": 2.9,
    "otica_selada": "Não Selada",
    "input_lag_ms": 140.0,
    "ajuste_brilho": "Não",
    "autofoco": "Não",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 47,
    "conectividade": "HDMI/USB/P2/RJ45/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/EM5aecv_uGw",
    "suporte_giratorio": true,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 380,
    "preco_max": 450,
    "ali_url": "https://s.click.aliexpress.com/e/_c3HlrLb5",
    "ali_cupom_loja": "SCHARD80F",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Thundeal",
    "modelo": "TD92 Pro",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 380,
    "audio_w": "5",
    "distancia_100pol": "3m",
    "distancia_100pol_m": 3.0,
    "otica_selada": "Não Selada",
    "input_lag_ms": 35.0,
    "ajuste_brilho": "Não",
    "autofoco": "Não",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 85,
    "conectividade": "2xHDMI/2xUSB/SAÍDA/ENTRADA/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/axH4F0utXps",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 630,
    "preco_max": 700,
    "ali_url": "https://s.click.aliexpress.com/e/_c4sRyqo7",
    "ali_cupom_loja": "SCHARD92F",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Thundeal",
    "modelo": "TD95W",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 505,
    "audio_w": "8",
    "distancia_100pol": "3.0m",
    "distancia_100pol_m": 3.0,
    "otica_selada": "Selada-",
    "input_lag_ms": 60.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 100,
    "conectividade": "2xHDMI/2xUSB/RJ45/ENTRADA/PORTA/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/cHnlfpOnbSs",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 620,
    "preco_max": 800,
    "ali_url": "https://s.click.aliexpress.com/e/_c3csE8Tt",
    "ali_cupom_loja": "SCHARD95F",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 32,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Thundeal",
    "modelo": "TD98PRO",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 60hz/1080p 120hz",
    "brilho_ansi": 1210,
    "audio_w": "2x15",
    "distancia_100pol": "2.8m",
    "distancia_100pol_m": 2.8,
    "otica_selada": "Selada-",
    "input_lag_ms": 10.0,
    "ajuste_brilho": "Sim",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 190,
    "conectividade": "2xHDMI/USB/RJ45/2xENTRADA/WiFi/BT",
    "tecnologias": "HDR10, HDR",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/dk52kJiPofc",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "6h",
    "preco_min": 1170,
    "preco_max": 1700,
    "ali_url": "https://s.click.aliexpress.com/e/_c34NeOVV",
    "ali_cupom_loja": "SCHARD98P1",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 32,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Thundeal",
    "modelo": "TD98PRO ATV",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 1300,
    "audio_w": "2x15",
    "distancia_100pol": "2.8m",
    "distancia_100pol_m": 2.8,
    "otica_selada": "Selada-",
    "input_lag_ms": 40.0,
    "ajuste_brilho": "Sim",
    "autofoco": "Sim",
    "sistema_operacional": "Android TV",
    "consumo_w": 200,
    "conectividade": "2xHDMI/USB/SPDIF/PORTA/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/SqYwJImh-hU",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "6h",
    "preco_min": 1320,
    "preco_max": 1900,
    "ali_url": "https://s.click.aliexpress.com/e/_c4mvy283",
    "ali_cupom_loja": "SCHARD98PAF",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Thundeal",
    "modelo": "TD98W",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 730,
    "audio_w": "15",
    "distancia_100pol": "3m",
    "distancia_100pol_m": 3.0,
    "otica_selada": "Selada",
    "input_lag_ms": 130.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 170,
    "conectividade": "2xHDMI/2xUSB/RJ45/2xENTRADA/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/WEbaQmy4Gjw",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "8h",
    "preco_min": 1050,
    "preco_max": 1500,
    "ali_url": "https://s.click.aliexpress.com/e/_olhrAyL",
    "ali_cupom_loja": "BRBR15A",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Touyinger",
    "modelo": "ET32",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 30hz",
    "brilho_ansi": 340,
    "audio_w": "5",
    "distancia_100pol": "3.1m",
    "distancia_100pol_m": 3.1,
    "otica_selada": "Não Selada",
    "input_lag_ms": 25.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 95,
    "conectividade": "2xHDMI/USB/AV/P2/WiFi/BT",
    "tecnologias": "Dolby Audio",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/hgvp0t3_occ",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 800,
    "preco_max": 850,
    "ali_url": "https://s.click.aliexpress.com/e/_mOTbB8R",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Touyinger",
    "modelo": "L9W Ultra",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 250,
    "audio_w": "3",
    "distancia_100pol": "2.4m",
    "distancia_100pol_m": 2.4,
    "otica_selada": "Não Selada",
    "input_lag_ms": 120.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 47,
    "conectividade": "HDMI/USB/P2/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/S8yGCgKlGyY",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 440,
    "preco_max": 500,
    "ali_url": "https://s.click.aliexpress.com/e/_c3gZsecB",
    "ali_cupom_loja": "CPSAC60K5GD6",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 32,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Touyinger",
    "modelo": "Q13W",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 60hz",
    "brilho_ansi": 1700,
    "audio_w": "3x12",
    "distancia_100pol": "2.8m",
    "distancia_100pol_m": 2.8,
    "otica_selada": "Selada",
    "input_lag_ms": 35.0,
    "ajuste_brilho": "Sim",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 200,
    "conectividade": "HDMI/2xUSB/P2/RJ45/WiFi/BT",
    "tecnologias": "HDR10, MEMC",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/Ytph-SPWI8Q",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "8h",
    "preco_min": 1350,
    "preco_max": 1750,
    "ali_url": "https://s.click.aliexpress.com/e/_c2wXytuJ",
    "ali_cupom_loja": "08QY3NO2MIHU",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 3,
    "armazenamento_gb": 128,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Vevshao",
    "modelo": "A10",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1280x720",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 250,
    "audio_w": "5",
    "distancia_100pol": "2.9m",
    "distancia_100pol_m": 2.9,
    "otica_selada": "Não Selada",
    "input_lag_ms": 180.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 70,
    "conectividade": "HDMI/USB/P2/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/06so18wPovE",
    "suporte_giratorio": true,
    "audio_qualidade": "",
    "uso_continuo": "4h",
    "preco_min": 661,
    "preco_max": 1000,
    "ali_url": "https://s.click.aliexpress.com/e/_c3zgYT7v",
    "ali_cupom_loja": "A10SCHA10",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "https://s.shopee.com.br/4qCF7jiXx5",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Vevshao",
    "modelo": "A22",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 60hz",
    "brilho_ansi": 740,
    "audio_w": "2x10",
    "distancia_100pol": "2.6m",
    "distancia_100pol_m": 2.6,
    "otica_selada": "Selada",
    "input_lag_ms": 40.0,
    "ajuste_brilho": "Sim",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 114,
    "conectividade": "HDMI/USB/P2/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/AnlEMUrdf68",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "6h",
    "preco_min": 850,
    "preco_max": 1100,
    "ali_url": "https://s.click.aliexpress.com/e/_c2vwwgof",
    "ali_cupom_loja": "A22BRDR",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "https://s.shopee.com.br/6VKT6jvPsj",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 32,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Vevshao",
    "modelo": "V60",
    "tecnologia": "DLP LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 60hz",
    "brilho_ansi": 450,
    "audio_w": "2x10",
    "distancia_100pol": "2.8m",
    "distancia_100pol_m": 2.8,
    "otica_selada": "Selada++",
    "input_lag_ms": 25.0,
    "ajuste_brilho": "Sim",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 60,
    "conectividade": "HDMI/2xUSB/P2/USB-C/WiFi/BT",
    "tecnologias": "HDR10, MEMC",
    "bateria": true,
    "cap_bateria": "20080mAh",
    "video_url": "https://youtu.be/5XqrcPf5dA8",
    "suporte_giratorio": true,
    "audio_qualidade": "",
    "uso_continuo": "12h",
    "preco_min": 1900,
    "preco_max": 2200,
    "ali_url": "https://s.click.aliexpress.com/e/_c3tlQfLv",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 32,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Voxflix",
    "modelo": "VF71",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 580,
    "audio_w": "5",
    "distancia_100pol": "3.0m",
    "distancia_100pol_m": 3.0,
    "otica_selada": "Não Selada",
    "input_lag_ms": 40.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 130,
    "conectividade": "HDMI/USB/AV/VGA/RJ45/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/1soF7qRHsCo",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "6h",
    "preco_min": 640,
    "preco_max": 800,
    "ali_url": "https://s.click.aliexpress.com/e/_mP6MKDl",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 32,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Wanbo",
    "modelo": "Dali 1",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1280x720",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 180,
    "audio_w": "2x5",
    "distancia_100pol": "2.7m",
    "distancia_100pol_m": 2.7,
    "otica_selada": "Não Selada+",
    "input_lag_ms": 50.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 70,
    "conectividade": "HDMI/USB/P2/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/zSP6EogWESE",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "6h",
    "preco_min": 800,
    "preco_max": 1000,
    "ali_url": "https://s.click.aliexpress.com/e/_c3IS4imr",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "MAES4",
    "ml_url": "https://meli.la/2zHB1c2",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Wanbo",
    "modelo": "DaVinci 1",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 490,
    "audio_w": "2x8",
    "distancia_100pol": "2.8m",
    "distancia_100pol_m": 2.8,
    "otica_selada": "Selada+",
    "input_lag_ms": 55.0,
    "ajuste_brilho": "Sim",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 100,
    "conectividade": "HDMI/2xUSB/P2/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/Xcte5PhoouI",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "8h",
    "preco_min": null,
    "preco_max": null,
    "ali_url": "",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 32,
    "status": "descontinuado",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Wanbo",
    "modelo": "Mozart 1",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 550,
    "audio_w": "2x8",
    "distancia_100pol": "2.7m",
    "distancia_100pol_m": 2.7,
    "otica_selada": "Selada+",
    "input_lag_ms": 40.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 120,
    "conectividade": "HDMI/2xUSB/P2/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/zBC6WivFmII",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "8h",
    "preco_min": null,
    "preco_max": null,
    "ali_url": "",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 32,
    "status": "descontinuado",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Wanbo",
    "modelo": "T2 Max New",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 220,
    "audio_w": "2x3",
    "distancia_100pol": "2.5m",
    "distancia_100pol_m": 2.5,
    "otica_selada": "Selada+",
    "input_lag_ms": 40.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Android não homologado",
    "consumo_w": 57,
    "conectividade": "HDMI/USB/P2/WiFi/BT",
    "tecnologias": "",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/VdVrZr5rJvQ",
    "suporte_giratorio": true,
    "audio_qualidade": "",
    "uso_continuo": "8h",
    "preco_min": null,
    "preco_max": null,
    "ali_url": "",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 16,
    "status": "descontinuado",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Wanbo",
    "modelo": "T2 Ultra",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 280,
    "audio_w": "2x3",
    "distancia_100pol": "2.8m",
    "distancia_100pol_m": 2.8,
    "otica_selada": "Selada+",
    "input_lag_ms": 50.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Android TV",
    "consumo_w": 53,
    "conectividade": "HDMI/USB/P2/WiFi/BT",
    "tecnologias": "HDR10",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/NaqNoDitcSY",
    "suporte_giratorio": true,
    "audio_qualidade": "",
    "uso_continuo": "8h",
    "preco_min": 1350,
    "preco_max": 1550,
    "ali_url": "",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "",
    "ml_url": "https://meli.la/1v3Rrbj",
    "shopee_url": "https://s.shopee.com.br/9fHTja51mj",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Wanbo",
    "modelo": "Vali 1",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 60hz",
    "brilho_ansi": 500,
    "audio_w": "2x6",
    "distancia_100pol": "2.9m",
    "distancia_100pol_m": 2.9,
    "otica_selada": "Selada-",
    "input_lag_ms": 50.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Android TV",
    "consumo_w": 110,
    "conectividade": "HDMI/USB/P2/WiFi/BT",
    "tecnologias": "HDR10",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/L_0ajiDrnUI",
    "suporte_giratorio": true,
    "audio_qualidade": "",
    "uso_continuo": "8h",
    "preco_min": 1680,
    "preco_max": 1990,
    "ali_url": "",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "",
    "ml_url": "https://meli.la/1AAe5HZ",
    "shopee_url": "https://s.shopee.com.br/8fOwXqtyd3",
    "amazon_url": "",
    "ram_gb": 1,
    "armazenamento_gb": 8,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Wanbo",
    "modelo": "X5 Pro",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "4k 60hz",
    "brilho_ansi": 570,
    "audio_w": "2x6",
    "distancia_100pol": "2.8m",
    "distancia_100pol_m": 2.8,
    "otica_selada": "Não Selada++",
    "input_lag_ms": 25.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Google TV",
    "consumo_w": 120,
    "conectividade": "HDMI/2xUSB/P2/WiFi/BT",
    "tecnologias": "HDR10",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/OHfd8EzoRX8",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "8h",
    "preco_min": 2000,
    "preco_max": 2600,
    "ali_url": "",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "",
    "ml_url": "https://meli.la/1ywAF3b",
    "shopee_url": "https://s.shopee.com.br/7fWPM8FmmU",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 32,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  },
  {
    "marca": "Wupro",
    "modelo": "G2",
    "tecnologia": "LCD LED",
    "resolucao_nativa": "1920x1080",
    "resolucao_max": "1080p 120hz",
    "brilho_ansi": 230,
    "audio_w": "2x3",
    "distancia_100pol": "2.6m",
    "distancia_100pol_m": 2.6,
    "otica_selada": "Selada+",
    "input_lag_ms": 10.0,
    "ajuste_brilho": "Não",
    "autofoco": "Sim",
    "sistema_operacional": "Google TV",
    "consumo_w": 60,
    "conectividade": "HDMI/USB/P2/WiFi/BT",
    "tecnologias": "HDR10, MEMC, Dolby Audio",
    "bateria": false,
    "cap_bateria": "",
    "video_url": "https://youtu.be/JDaLnPoS4jk",
    "suporte_giratorio": false,
    "audio_qualidade": "",
    "uso_continuo": "8h",
    "preco_min": 850,
    "preco_max": 920,
    "ali_url": "https://s.click.aliexpress.com/e/_opyTQ2Z",
    "ali_cupom_loja": "",
    "ali_cupom_promo": "MAES4",
    "ml_url": "",
    "shopee_url": "",
    "amazon_url": "",
    "ram_gb": 2,
    "armazenamento_gb": 12,
    "status": "nacional",
    "link_importado": "",
    "bolsa": ""
  }
];
